accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('register', views.user_register, name="user_register"),
    path('login', views.user_login, name="user_login"),
    path('logout', views.user_logout, name="user_logout"),
]

bestoon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls", namespace="web")),
    path('accounts/', include("accounts.urls", namespace="accounts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'web.views.error_404'

web/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
    path('', views.home, name="home"),
    path('income/detail/<int:income_id>', views.income_detail, name="income_detail"),
    path('expense/detail/<int:expense_id>', views.expense_detail, name="expense_detail"),
    path('income/delete/<int:income_id>', views.income_delete, name="income_delete"),
    path('expense/delete/<int:expense_id>', views.expense_delete, name="expense_delete"),
    path('income/create', views.income_create, name="income_create"),
    path('expense/create', views.expense_create, name="expense_create"),
    path('income/edit/<int:income_id>', views.income_update, name="income_update"),
    path('expense/edit/<int:income_id>', views.expense_update, name="expense_update"),
]

templates/includes/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'web:home' %}">بستون</a>
        {% if request.user.is_authenticated %}
        <a class="btn btn-outline-danger" href="{% url 'accounts:user_logout' %}" style="color:white">خروج از سایت</a>
        {% else %}
        <a class="btn btn-outline-info" href="{% url 'accounts:user_register' %}" style="margin-right: 10px;margin-right: 1500px;color: white;">ثبت نام</a>
        <a class="btn btn-outline-primary" href="{% url 'accounts:user_login' %}" style="float: left;color:white;">ورود به سایت</a>
        {% endif %}
    </div>
</nav>