bestoon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls", namespace="web")),
    path('accounts/', include("accounts.urls", namespace="accounts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'web.views.error_404'

web/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
    path('', views.home, name="home"),
    path('income/detail/<int:income_id>', views.income_detail, name="income_detail"),
    path('expense/detail/<int:expense_id>', views.expense_detail, name="expense_detail"),
    path('income/delete/<int:income_id>', views.income_delete, name="income_delete"),
    path('expense/delete/<int:expense_id>', views.expense_delete, name="expense_delete"),
    path('income/create', views.income_create, name="income_create"),
    path('expense/create', views.expense_create, name="expense_create"),
    path('income/edit/<int:income_id>', views.income_update, name="income_update"),
    path('expense/edit/<int:income_id>', views.expense_update, name="expense_update"),
]

web/templates/web/expense_create.html
{% extends 'base.html' %}

{% block title %}<title>ساخت خرج | بستون</title>{% endblock %}


{% block content %}
<h1>ساخت خرج</h1>
<form action="{% url 'web:expense_create' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-outline-primary" value="ساخت">
</form>
{% endblock %}

web/templates/web/expense_detail.html
{% extends 'base.html' %}

{% block title %}<title>جزئیات خرج | بستون</title>{% endblock %}

{% block content %}
{% for expense in expenses %}
<h1>{{expense.title}}</h1>
<hr />
مقدار: {{expense.amount}} تومان<hr />
<b><h4>تاریخ ثبت: {{expense.created.date}}</h4></b>
<b><h4>تاریخ تغییر: {{expense.updated.date}}</h4></b>
<hr />
<b><h4>زمان ثبت: {{expense.created.time}}</h4></b>
<b><h4>زمان تغییر: {{expense.updated.time}}</h4></b><hr />
<h1>قابلیت ها</h1>
<a href="{% url 'web:expense_delete' expense.id %}" class="btn btn-danger">حذف خرج</a>
<a href="{% url 'web:expense_update' expense.id %}" class="btn btn-info">تغییر خرج</a>
{% endfor %}
{% endblock %}

web/templates/web/expense_edit.html
{% extends 'base.html' %}

{% block title %}<title>تغییر خرج | بستون</title>{% endblock %}

{% block content %}

<h1>تغییر خرج</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-outline-primary" value="تغییر">
</form>


{% endblock %}

web/templates/web/income_create.html
{% extends 'base.html' %}

{% block title %}<title>ساخت درآمد | بستون</title>{% endblock %}


{% block content %}
<h1>ساخت درآمد</h1>
<form action="{% url 'web:income_create' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-outline-primary" value="ساخت">
</form>
{% endblock %}

web/templates/web/income_detail.html
{% extends 'base.html' %}

{% block title %}<title>جزئیات درآمد | بستون</title>{% endblock %}

{% block content %}
{% for income in incomes %}
<h1>{{income.title}}</h1>
<hr />
مقدار: {{income.amount}} تومان<hr />
<b><h4>تاریخ ثبت: {{income.created.date}}</h4></b>
<b><h4>تاریخ تغییر: {{income.updated.date}}</h4></b>
<hr />
<b><h4>زمان ثبت: {{income.created.time}}</h4></b>
<b><h4>زمان تغییر: {{income.updated.time}}</h4></b><hr />
<h1>قابلیت ها</h1>
<a href="{% url 'web:income_delete' income.id %}" class="btn btn-danger">حذف درآمد</a>
<a href="{% url 'web:income_update' income.id %}" class="btn btn-info">تغییر درآمد</a>
{% endfor %}
{% endblock %}

web/templates/web/income_edit.html
{% extends 'base.html' %}

{% block title %}<title>تغییر درآمد | بستون</title>{% endblock %}

{% block content %}

<h1>تغییر درآمد</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-outline-primary" value="تغییر">
</form>


{% endblock %}

web/templates/web/index.html
{% extends 'base.html' %}

{% block title %}<title>بستون | صفحه اصلی</title>{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}
<h1>خرج ها: </h1><br />
<a href="{% url 'web:expense_create' %}" class="btn btn-outline-info">ساخت خرج</a><hr />
{% if expenses %}
{% for expense in expenses %}
{% if expense.user == request.user %}
<ul class="list-group list-group-flush">
<li class="list-group-item"><a href="{% url 'web:expense_detail' expense.id %}">{{expense.title}}</a><hr /></li>
</ul>
{% endif %}
{% endfor %}
{% else %}
<p class="alert alert-warning">بدون خرج</p>
{% endif %}
<hr />
<h1>درآمد ها:</h1><br />
<a href="{% url 'web:income_create' %}" class="btn btn-outline-info">ساخت درآمد</a><hr />
{% if incomes %}
{% for income in incomes %}
{% if income.user == request.user %}
<ul class="list-group list-group-flush">
<li class="list-group-item"><a href="{% url 'web:income_detail' income.id %}">{{income.title}}</a><hr /></li>
</ul>
{% endif %}
{% endfor %}
{% else %}
<p class="alert alert-warning">بدون درآمد</p>
{% endif %}
{% else %}
<h1 class="alrt alert-warning">برای استفاده از سایت باید ورود کرده باشید</h1>
{% endif %}
{% endblock %}